---
gcp_project:  
gcp_cred_kind: serviceaccount
gcp_cred_file: credentials.json
region: 
zone: 
instance_config:
  - vm_name: "ansible-controlnode"
    vm_machine_type: "n1-standard-1"
    vm_address_name: "ansible-controlnode-address"
    vm_group: "ansible"
    disk_name: "ansible-controlnode-disk"
    disk_size: "20"
  - vm_name: "ansible-node0"
    vm_machine_type: "n1-standard-1"
    vm_address_name: "ansible-node0-address"
    vm_group: "ansible"
    disk_name: "ansible-node0-disk"
    disk_size: "20"
  - vm_name: "ansible-node1"
    vm_machine_type: "n1-standard-1"
    vm_address_name: "ansible-node1-address"
    vm_group: "ansible"
    disk_name: "ansible-node1-disk"
    disk_size: "20"
  - vm_name: "ansible-node2"
    vm_machine_type: "n1-standard-1"
    vm_address_name: "ansible-node2-address"
    vm_group: "ansible"
    disk_name: "ansible-node2-disk"
    disk_size: "20"
